### ISSUE TITLE
Recursive execution of real-time hook when filter option is passed.

### ISSUE THREAD

**Issue by herbievine** [tmm/react-supabase#27]
# Bug report

## Description / Observed Behavior

Recursive execution of real-time hook when filter option is passed.

## Expected Behavior

Open a websocket connection and subscribe to changes

## Repro Steps / Code Example

```
const Chats: React.FC<ITabsProps<'Chats'>> = ({}) => {
  const [{ data }] = useRealtime<DB.Member>(
    'members',
    {
      select: {
        columns: 'id',
        filter: (query) => query.eq('userId', '94a9aa95-c794-404a-9a37-7f424b215ebb'), // Works when this line is removed
      },
    }
  )

  useEffect(() => console.log(data), [data])

  return (...)
}
```

## Additional Context

```
{
    "@supabase/supabase-js": "^1.24.0",
    "expo": "~42.0.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-supabase": "^0.2.0"
  }
```

This might be a fault of mine. I can't read the HTTP request or console logs as Firefox just breaks when I execute this.

**Comment by maxkrieger** [comment]
To clarify for others: don't use `useSelect`, pass in `{select: {filter}}` to `useRealtime`
