### ISSUE TITLE
Promises never reject - exceptions are swallowed

### ISSUE THREAD

**Issue by bruceharrison1984** [tmm/react-supabase#33]
# Bug report

## Description / Observed Behavior
Use something like `useInsert` and force an error (insert null value in required column). Either wrap the call in a try/catch block, or utilize the `.catch` syntax for callbacks. The catch block never hits. The exception is swallowed, and returned in the `errors` property instead. This is not the behavior I would expect, because any libraries that can be used with promises (react-toastify in my case) cannot be directly used with this library.

## Expected Behavior
I would expect exceptions to propagate up as they traditionally do, or provide some means to opt-out of this behavior.

## Repro Steps / Code Example
```js
const [_, insertEvent] = useInsert<CalendarEvent>('calendar_event');

try {
  const insertFunc = await insertEvent({
    // insert nothing to force a validation error
  })
  } catch (err) {
    console.log(err) //<-- this will never be hit
  }

  const insertFunc = await insertEvent({
    // insert nothing to force a validation error
  }).catch(error => {
    console.log(error); // <-- this will never be hit
  });
```

## Additional Context
The issue can be worked around by wrapping the call
```js
  const insertFunc = async () => {
    const { data, count, error } = await insertEvent({
      // force error
    })
    if (error) throw error;
    return { data, count };
  }
```

This could be made suitably generic to wrap any call, but feels like this shouldn't be necessary.

**Comment by gianelli99** [comment]
Hi there! Maybe this comment arrives a bit late.

Have you tried with `shouldThrowOnError` option set to `true` when creating the supabase client?
Something like this:
```
const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key", { shouldThrowOnError: true })
```
I found this property [here](https://github.com/supabase/supabase-js/blob/master/src/lib/types.ts#:~:text=shouldThrowOnError%3F%3A%20boolean), I hope it helps you.

**Comment by bruceharrison1984** [comment]
@gianelli99 Wow, I totally overlooked that property. I'll give it a go, but I suspect it'll solve my issue. Thanks for your work on this!
