### ISSUE TITLE
Error following useAuth guide

### ISSUE THREAD

**Issue by zapbra** [tmm/react-supabase#63]
**Error message:**
![err1](https://user-images.githubusercontent.com/84364656/203613436-edc4eef8-f2e6-47bc-8753-da3aad443c22.PNG)

**Code used:**
![err2](https://user-images.githubusercontent.com/84364656/203613449-c2fe7aba-089d-443c-9032-96782e50796e.PNG)
![err3](https://user-images.githubusercontent.com/84364656/203613467-732d8072-fb4e-4133-94fd-c3b9d2b8a3c9.PNG)

**Comment by tmm** [comment]
Looks like you need to wrap your app in the [`Provider`](https://react-supabase.vercel.app/documentation/provider)
