### ISSUE TITLE
useAuthStateChange fails in @supabase/supabase-js v2+

### ISSUE THREAD

**Issue by a11rew** [tmm/react-supabase#66]
# Bug report

useAuthStateChange fails in @supabase/supabase-js v2+

## Description / Observed Behavior

The `useAuthStateChange` hook throws a `n.unsubscribe is not a function` error on v2 versions of `supabase/supabase-js`.  

## Expected Behavior

Hook does not throw page breaking error and returns documented values. 

## Repro Steps / Code Example
https://codesandbox.io/s/sharp-snow-vdzivd?file=/src/App.tsx:311-312

## Additional Context

`react-supabase` version - `0.2.0`
`@supabase/supabase-js` - 2.2.3

The authStateChanged listener has [since been updated](https://github.com/supabase/gotrue-js/blame/2d60e79073b96ae8c97a6ce18e2601ed1e2a2712/src/GoTrueClient.ts#L848) to return a `subscription` object with the unsubscribe function. 

I guess this is a question of compatibility since this library is only rated for v1 but are there plans for v2 support and or are PRs updating the existing hooks welcome?

**Comment by tmm** [comment]
No plans to support v2 right now. Other projects currently keeping me busy.
